### ISSUE TITLE
RecordFieldTimestampExtractor does not tolerate string timestamps without milliseconds

### ISSUE THREAD

**Issue by robobario** [confluentinc/kafka-connect-storage-common#61]
Our application is emitting ISO8601 timestamps using java.util.Instant, and our kafka connect hdfs sink is barfing when it hits a timestamp without milliseconds:

`java.lang.IllegalArgumentException: Invalid format: "2015-04-02T01:00:00Z" is malformed at "Z`

jodatime's `ISODateTimeFormat.dateTime()` does not support millis but it has a `ISODateTimeFormat.dateTimeParser()` that supports both millis or no millis, [here's a discussion](https://github.com/JodaOrg/joda-time/issues/97) about it.

**Comment by kkonstantine** [comment]
Feature was merged in `4.1.x` and later. Closing here, but feel free to reopen if the fix doesn't work for you.
